In [9]:
#!pip install -e .

In [1]:
!pip install danda

Requirement already satisfied: danda in /home/mohammad/learn/danda/src (0.1.2a2)
Requirement already satisfied: pandas>=2.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (3.0.3)
Requirement already satisfied: numpy>=1.26 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (2.4.4)
Requirement already satisfied: build in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (1.4.2)
Requirement already satisfied: twine in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (6.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from pandas>=2.2->danda) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=2.2->danda) (1.17.0)
Requirement already satisfied: packaging>=24.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from build->danda) (26.0)
Requirement already satisfied: pyproject_hooks in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from build->danda) (1.2.0)
Requirement already satisfied: readme-renderer>=35.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (45.0)
Requirement already satisfied: requests>=2.20 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.33.1)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (1.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.6.3)
Requirement already satisfied: keyring>=21.2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (25.7.0)
Requirement already satisfied: rfc3986>=1.4.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.0.0)
Requirement already satisfied: rich>=12.0.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (14.3.3)
Requirement already satisfied: id in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (1.6.1)
Requirement already satisfied: SecretStorage>=3.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (3.5.0)
Requirement already satisfied: jeepney>=0.4.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (0.9.0)
Requirement already satisfied: jaraco.classes in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (3.4.0)
Requirement already satisfied: jaraco.functools in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (4.6.0)
Requirement already satisfied: jaraco.context in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (6.1.2)
Requirement already satisfied: nh3>=0.2.14 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (0.3.6)
Requirement already satisfied: docutils>=0.21.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (0.23)
Requirement already satisfied: Pygments>=2.5.1 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (2.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from rich>=12.0.0->twine->danda) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->twine->danda) (0.1.2)
Requirement already satisfied: cryptography>=2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (46.0.6)
Requirement already satisfied: cffi>=2.0.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (2.0.0)
Requirement already satisfied: pycparser in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (3.0)
Requirement already satisfied: more-itertools in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from jaraco.classes->keyring>=21.2.0->twine->danda) (11.1.0)

## clean
This example shows empty rows clean

In [4]:
from pprint import pprint
import numpy as np
import pandas as pd
# notice the need to danda import to have accessor df
import danda # noqa: F401  # registers the pandas accessor

data = pd.DataFrame({
    "Name": ["Alice", np.nan, "Charlie", np.nan, "Eve"],
    "Age": [25, np.nan, np.nan, np.nan, 30],
    "City": ["New York", np.nan, "Chicago", np.nan, np.nan],
})
data = data.dg.clean()
pprint(data.dg.report)
data

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(236),
                                                      'before_bytes': np.int64(284),
                                                      'saved_bytes': np.int64(48),
                                                      'saved_percent': np.float64(16.901408450704224)},
                                     'plugin_names': ['EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates',
                                                      'EmptySpacesPlugin'],
                                     'plugins_count': 4}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 0',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 0',
                     'EmptyRowsPlugin': 'Number of deleted rows: 2',
                     'EmptySpacesPlugin': 'No leading or trailing whitespace '
                                          'found.'}}}

      Name   Age      City
0    Alice  25.0  New York
2  Charlie   NaN   Chicago
4      Eve  30.0       NaN

In [12]:
# Empty columns
data = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [np.nan, np.nan, np.nan],  # Entirely empty
    "C": [4, np.nan, 6],
    "D": [np.nan, np.nan, np.nan],  # Entirely empty
})
data = data.dg.clean()
print(data.dg.report)
data

{'chain': {'ChainPlugin': "Number of plugins: 4\n report: {'clean': {'EmptyRowsPlugin': 'Number of deleted rows: 0', 'EmptyColumnsPlugin': 'Number of deleted columns: 2', 'DropDuplicates': 'Number of deleted rows: 0', 'EmptySpacesPlugin': 'No leading or trailing whitespace found.'}}"}}

   A    C
0  1  4.0
1  2  NaN
2  3  6.0

In [5]:
# drop duplicates
df = pd.DataFrame({
    "A": [1, 2, 2, 3],
    "B": ["a", "b", "b", "c"],
})

df = df.dg.clean()
pprint(df.dg.report)
df

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(76),
                                                      'before_bytes': np.int64(200),
                                                      'saved_bytes': np.int64(124),
                                                      'saved_percent': np.float64(62.0)},
                                     'plugin_names': ['EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates',
                                                      'EmptySpacesPlugin'],
                                     'plugins_count': 4}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 1',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 0',
                     'EmptyRowsPlugin': 'Number of deleted rows: 0',
                     'EmptySpacesPlugin': 'No leading or trailing whitespace '
                                          'found.'}}}

   A  B
0  1  a
1  2  b
3  3  c

In [6]:
# clean white spaces in string columns
df = pd.DataFrame(
    {
        "name": [" Alice ", "Bob  ", "  Charlie"],
        "city": [" London", "Paris ", " Berlin "],
    }
)
df = df.dg.clean()
pprint(df.dg.report)
df

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(214),
                                                      'before_bytes': np.int64(222),
                                                      'saved_bytes': np.int64(8),
                                                      'saved_percent': np.float64(3.6036036036036037)},
                                     'plugin_names': ['EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates',
                                                      'EmptySpacesPlugin'],
                                     'plugins_count': 4}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 0',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 0',
                     'EmptyRowsPlugin': 'Number of deleted rows: 0',
                     'EmptySpacesPlugin': 'Stripped leading/trailing '
                                          'whitespace from columns: name, '
                                          'city'}}}

      name    city
0    Alice  London
1      Bob   Paris
2  Charlie  Berlin