In [1]:
!pip install danda

Requirement already satisfied: danda in /home/mohammad/learn/danda/src (0.1.2a2)
Requirement already satisfied: pandas>=2.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (3.0.3)
Requirement already satisfied: numpy>=1.26 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (2.4.4)
Requirement already satisfied: build in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (1.4.2)
Requirement already satisfied: twine in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from danda) (6.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from pandas>=2.2->danda) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=2.2->danda) (1.17.0)
Requirement already satisfied: packaging>=24.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from build->danda) (26.0)
Requirement already satisfied: pyproject_hooks in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from build->danda) (1.2.0)
Requirement already satisfied: readme-renderer>=35.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (45.0)
Requirement already satisfied: requests>=2.20 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.33.1)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (1.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.6.3)
Requirement already satisfied: keyring>=21.2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (25.7.0)
Requirement already satisfied: rfc3986>=1.4.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (2.0.0)
Requirement already satisfied: rich>=12.0.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (14.3.3)
Requirement already satisfied: id in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from twine->danda) (1.6.1)
Requirement already satisfied: SecretStorage>=3.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (3.5.0)
Requirement already satisfied: jeepney>=0.4.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (0.9.0)
Requirement already satisfied: jaraco.classes in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (3.4.0)
Requirement already satisfied: jaraco.functools in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (4.6.0)
Requirement already satisfied: jaraco.context in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from keyring>=21.2.0->twine->danda) (6.1.2)
Requirement already satisfied: nh3>=0.2.14 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (0.3.6)
Requirement already satisfied: docutils>=0.21.2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (0.23)
Requirement already satisfied: Pygments>=2.5.1 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from readme-renderer>=35.0->twine->danda) (2.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from requests>=2.20->twine->danda) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from rich>=12.0.0->twine->danda) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->twine->danda) (0.1.2)
Requirement already satisfied: cryptography>=2.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (46.0.6)
Requirement already satisfied: cffi>=2.0.0 in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (2.0.0)
Requirement already satisfied: pycparser in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->danda) (3.0)
Requirement already satisfied: more-itertools in /home/mohammad/anaconda3/envs/ai/lib/python3.13/site-packages (from jaraco.classes->keyring>=21.2.0->twine->danda) (11.1.0)

In [2]:
import numpy as np
import pandas as pd
# notice the need to danda import to have accessor df
import danda # noqa: F401  # registers the pandas accessor

In [3]:
df = pd.DataFrame({
    "name": [
        "Alice",
        "   ",      # -> "" -> pd.NA
        "Bob",
    ],
    "city": [
        "Berlin",
        " NULL ",   # -> "NULL" -> pd.NA
        "London",
    ],
    "empty_column": [
        " ",
        " ",
        " ",
    ],
})
df

    name    city empty_column
0  Alice  Berlin
1          NULL
2    Bob  London

In [4]:
from pprint import pprint

clean_df = df.dg.clean()
pprint(clean_df.dg.report)
clean_df

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(186),
                                                      'before_bytes': np.int64(236),
                                                      'saved_bytes': np.int64(50),
                                                      'saved_percent': np.float64(21.1864406779661)},
                                     'plugin_names': ['EmptySpacesPlugin',
                                                      'NormalizeMissingValuesPlugin',
                                                      'EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates'],
                                     'plugins_count': 5}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 0',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 1',
                     'EmptyRowsPlugin': 'Number of deleted rows: 1',
                     'EmptySpacesPlugin': 'Stripped leading/trailing '
                                          'whitespace from columns: name, '
                                          'city, empty_column',
                     'NormalizeMissingValuesPlugin': 'Normalized 5 missing '
                                                     'value(s) across 3 '
                                                     'column(s).'}}}

    name    city
0  Alice  Berlin
2    Bob  London

In [3]:
df = pd.DataFrame(
    {
        "name": [
            " Alice ",    # leading/trailing whitespace
            "Bob",
            "Bob",        # duplicate row
            None,         # empty row (together with other None values)
            "Charlie",
        ],
        "city": [
            " London ",
            "Paris",
            "Paris",      # duplicate row
            None,
            " Berlin",
        ],
        "age": [
            30,
            25,
            25,           # duplicate row
            None,
            40,
        ],
        "empty_column": [
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
    }
)

# Make row 3 completely empty
df.loc[3] = [None, None, None, None]

print(df)

      name      city   age  empty_column
0   Alice    London   30.0           NaN
1      Bob     Paris  25.0           NaN
2      Bob     Paris  25.0           NaN
3      NaN       NaN   NaN           NaN
4  Charlie    Berlin  40.0           NaN

In [6]:
from pprint import pprint

clean_df = df.dg.clean()
pprint(clean_df.dg.report)
clean_df

{'clean': {'chain': {'ChainPlugin': {'memory_usage': {'after_bytes': np.int64(130),
                                                      'before_bytes': np.int64(339),
                                                      'saved_bytes': np.int64(209),
                                                      'saved_percent': np.float64(61.6519174041298)},
                                     'plugin_names': ['EmptyRowsPlugin',
                                                      'EmptyColumnsPlugin',
                                                      'DropDuplicates',
                                                      'EmptySpacesPlugin'],
                                     'plugins_count': 4}},
           'clean': {'DropDuplicates': 'Number of deleted rows: 1',
                     'EmptyColumnsPlugin': 'Number of deleted columns: 1',
                     'EmptyRowsPlugin': 'Number of deleted rows: 1',
                     'EmptySpacesPlugin': 'Stripped leading/trailing '
                                          'whitespace from columns: name, '
                                          'city'}}}

      name    city   age
0    Alice  London  30.0
1      Bob   Paris  25.0
4  Charlie  Berlin  40.0